###########################
##  VARIABLES CONSTANTES ##
###########################


LARGEUR, HAUTEUR = 600, 600 
DIMC = 20 # DIMENSION D'UNE CASE
NBPL = LARGEUR // DIMC # NOMBRE DE BLOC PAR LIGNE
FPRO = 2 # FREQUANCE DES NAISSANCES DES PROIES
DPRO =  8 # AGE DE VIE MAXIMUM POUR UNE PROIE
EDEPPRE = 10 # ENERGIE A LA NAISSANCE DES PREDATEURS
NRJREPROPRED = 50 # NIVEAU D'ENERGIE AUQUEL UN PREDATEUR PEUT SE REPRODUIRE
MIAM = 2 # NIVEAU D'ENERGIE GAGNE LORSQU'UN PREDATEUR MANGE UNE PROIE
FLAIR = 4 # INDIQUE LA DISTANCE MAXIMALE A LAQUELLE UN PREDATEUR PEUT SENTIR UNE PROIE
